### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by malikpiarali** [malikpiarali/manual-plan#4]
Application

- [x] Concluir wireframe da página de pesquisa com filtros.
- [ ] Passar wireframe para HTML.

Tooling

- [x] Fazer Git Real da CodeSchool (7/7).
- [x] Fazer tutorial Git-it da NodeSchool.

Language

- [X] CSS
- [X] HTML
- [x] Estudar http://getbootstrap.com/
  - [ ] (Ver videos no youtube de twitter bootstrap)
- [ ] JavaScript - https://www.codeschool.com/paths/javascript
  - [ ] JavaScript Language Path 
  - [ ] Server-side Frameworks

Extra (meaning, only after all of the above!)

- [ ] https://www.codeschool.com/paths/html-css

**Comment by diasdavid** [comment]
Bonus (for while you eat your cereal in the morning):
- https://www.youtube.com/watch?v=kDyJN7qQETA
- https://www.youtube.com/watch?v=9fHSbiCISOA

**Comment by malikpiarali** [comment]
@diasdavid Linux stopped working on my chromebook again. I have no clue of what's going on and therefore I've been using my windows-pc.

**Comment by malikpiarali** [comment]
@diasdavid Sorry for bothering, I just finished Git Real and I really liked it but I was only allowed to do 1 level out of 7. I will ask my dad if I can enrol on Code School for 1 month.

I will do the git it tutorial by nodeschool and afterwards I can do some course on Lynda.com or try Treehouse for 2 weeks. What do you think? Right now I don't feel like I master git at all...

**Comment by malikpiarali** [comment]
Just finished git-it tutorial by Nodeschool. I also watched the videos listed on https://www.bento.io/tracks/front-end#git-and-github.

Last but not least, Codeschool sent me a promotion code and I enrolled. Tomorrow I will be able to get real on Git for real. I'm starting to feel more confident about using Git.

**Comment by diasdavid** [comment]
No Lynda and no Treehouse, there are more tasks on the list for you to finish first.

Malik, focus.

**Comment by malikpiarali** [comment]
Deal. Today I will be studying bootstrap and finishing git real by CodeSchool. See you Thursday?

**Comment by malikpiarali** [comment]
Just finished Level 2 on Git Real of 7. Starting Level 3 now. Already watched some stuff about Boostrap.

**Comment by malikpiarali** [comment]
You're right @diasdavid. Just finished Git Real level 4 out of 7 on CodeSchool. Starting Level 5 now. Also watched some stuff about Boostrap, and web fundamentals on Bento.io while I was having dinner.

**Comment by malikpiarali** [comment]
I finished Git Real for real this time but I'm not feeling very confident about it @diasdavid. I can't stand not mastering a subject which I'm working on but I will move on to javascript.

**Comment by malikpiarali** [comment]
I will be using Gold Boostrap (http://www.goldbootstrap.com/) instead of the regular one. Hope you don't mind @diasdavid. 

In the following days I will not be doing any work at all so I will close this issue for now.

**Comment by diasdavid** [comment]
@malikpiarali issues should be closed when they are solved or no longer important
